### ISSUE TITLE
syntax highlighting 

### ISSUE THREAD

**Issue by LucyMcGowan** [LFOD/real-blog#43]
Why don't we have it?

**Comment by LucyMcGowan** [comment]
ping @nstrayer - can we update this?

**Comment by nstrayer** [comment]
Shur thing. [This](https://highlightjs.org/) seems to be the go to. I won't be able to do it for a bit but if you want to tackle it and get stuck I can certainly help. I'd prolly try adding it straight into `tuftesque`.

**Comment by LucyMcGowan** [comment]
DID IT
